spring:
  application:
    name: order-service-api
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}